web:
   build: .
   ports:
        - "8080:80"
   environment:
        - DB_HOST=db
        - DB_USER=ljohnsonjr
        - DB_PASS=Password01
        - DB_NAME=db
   links:
        - db
db:
   build: ./db
